<h1>Users</h1>

<?php if (count($flash) > 0) : ?>
    <?php foreach ($flash as $flashType => $flashMessages) : ?>
    <div class="<?= $flashType; ?>"><?= implode('<br>', $flashMessages); ?></div>
    <?php endforeach; ?>
<?php endif; ?>

<form action="<?= $routeFormUserSearch; ?>" method="GET">
    <input type='search' required name='term' value="<?= $term; ?>">
    <input type='submit' value="Search">
</form>

<ul>
<?php foreach ($users as $user) : ?>
    <li><a href="<?= $user['route']; ?>"><?= $user['nickname']; ?></a></li>
<?php endforeach; ?>
</ul>
