<?php if (!$isAuthorized) : ?>
    <h1>Login</h1>

    <form action="<?= $routeFormLogin; ?>" method="POST">
        <input type="text" name="login" value="">
        <input type="submit" value="Login">
    </form>
<?php else : ?>
    <form action="<?= $routeFormLogin; ?>" method="POST">
        <input type="hidden" name="_METHOD" value="DELETE">
        <input type="submit" value="Logout">
    </form>
<?php endif; ?>
