<h1>New user</h1>

<form action="<?= $routeFormCreateUser; ?>" method="POST">
    <div>
        <label>
            Nickname:
            <input type="text" name="user[nickname]" value="<?= $user['nickname']; ?>">
        </label>
        <?php if (isset($errors['nickname'])) : ?>
            <div><?= $errors['nickname']; ?></div>
        <?php endif; ?>
    </div>
    <div>
        <label>
            Email:
            <input type="email" required name="user[email]" value="<?= $user['email']; ?>">
        </label>
        <?php if (isset($errors['email'])) : ?>
            <div><?= $errors['email']; ?></div>
        <?php endif; ?>
    </div>
    <input type="submit" value="Submit">
</form>
